# .travis.yml
dist: precise

language: php

php:
  - 7.4

addons:
  mariadb: 10.4

cache:
  directories:
    - node_modules
    - vendor

before_script:
  - rm -rf composer.lock
  - composer install
  - cp .env.travis .env
  - sudo mysql -e 'CREATE DATABASE testing;'
  - php artisan migrate --no-interaction -vvv


script:
  - vendor/bin/phpunit
